config/routes.rb
RubyAMFRails3::Application.routes.draw do
  resources :comments

  resources :posts

end

app/models/action.rb
class Action < ActiveRecord::Base

  set_primary_key :code

end

app/models/category.rb
class Category < ActiveRecord::Base

  before_save        :set_child_foreign_keys
  after_update       :update_children

  register_amf :actionscript  => 'vos.Category',
               :ruby          => 'Category',
               :type          => 'active_record',
               :methods       => ["children"],
               :attributes    => ["id", "name", "post_id"]

  acts_as_nested_set :dependent => :destroy,
                    :scope     => :post_id

  # Before saving any child categories, this sets their foreign key to the parents foreign key
  def set_child_foreign_keys
    self.children.each do |child|
      child.post_id = self.post_id
    end
  end

  # Makes sure all changes to child properties are saved.
  # It also moves children to the parent if it is not currently a child of the parent.
  def update_children
    self.children.each do |child|
        child.update_children
        unless child.new_record?
          child.save
          child.move_to_child_of(self) if child.parent_id != self.id
        end
    end if self.changed?
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  register_amf :actionscript  => 'vos.Comment',
               :ruby          => 'Comment',
               :type          => 'active_record',
               :associations  => ["action"],
               :attributes    => ["id", "description", "post_id"]

  belongs_to :post

  belongs_to :action,
             :class_name => 'Action',
             :foreign_key => :code,
             :primary_key => :code

  validates_presence_of :action

end

app/models/moderator.rb
class Moderator < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base

  attr_accessor :test_attribute

  register_amf :actionscript  => 'vos.Post',
               :ruby          => 'Post',
               :type          => 'active_record',
               :associations  => ["comments", "author", "categories"],
               :attributes    => ["id", "name"]

  has_one  :author,
           :class_name => 'PostAuthor',
           :dependent => :destroy

  has_many :comments

  has_many :categories,
           :conditions => 'parent_id is null'

  has_many :moderators

  validates_associated  :comments
  validates_associated  :author
  validates_presence_of :author

  accepts_nested_attributes_for :author, :comments, :categories

end

app/models/post_author.rb
#require 'composite_primary_keys'
class PostAuthor < ActiveRecord::Base

  #set_primary_keys :post_id, :name

  register_amf :actionscript  => 'vos.PostAuthor',
               :ruby          => 'PostAuthor',
               :type          => 'active_record',
               :attributes    => ["post_id", "name", "description"]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #respond_to :xml, :html, :amf

  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.amf  { render :amf => @posts }
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.amf  { render :amf => @post}
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = is_amf ? params[:post] : Post.new(params[:post])

#    flash[:notice] = "Post successfully created" if @post.save
#    respond_with(@post) do |format|
#      format.amf  { render :amf => @post }
#      format.html { redirect_to(@post) }
#      format.xml  { render :xml => @post, :status => :created, :location => @post }
#    end

    #flash[:notice] = "Post successfully created" if @post.save
    respond_to do |format|
      if @post.save
      format.amf  { render :amf => @post, :class_mapping_scope =>'test'}
      format.html { redirect_to(@post) }
      format.xml  { render :xml => @post, :status => :created, :location => @post }
      end
    end

#    respond_to do |format|
#      if @post.save
#        flash[:notice] = 'Post was successfully created.'
#        format.amf  { render :amf => @post }
#        format.html { redirect_to(@post) }
#        format.xml  { render :xml => @post, :status => :created, :location => @post }
#      else
#        format.amf  { render :amf => FaultObject.new(@post.errors.full_messages.join('\n'))}
#        format.html { render :action => "new" }
#        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
#      end
#    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    if is_amf
      create
    else
      @post = Post.find(params[:id])

      respond_to do |format|
        if @post.update_attributes(params[:post])
          flash[:notice] = 'Post was successfully updated.'
          format.html { redirect_to(@post) }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rubyamf_helper.rb
#This is just a stub file so Rails doesn't complain about me not being in the helpers folder
module RubyamfHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br />
    <%= f.text_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Post</th>
    <th>Code</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.post_id %></td>
    <td><%= comment.code %></td>
    <td><%= comment.description %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Post:</b>
  <%= @comment.post_id %>
</p>

<p>
  <b>Code:</b>
  <%= @comment.code %>
</p>

<p>
  <b>Description:</b>
  <%= @comment.description %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyamfRails3Testing</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>